name: Metrics
run-name: Generating Github Metrics CLI theme

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow when pushing on main
  push:
    branches:
      - main

jobs:
  github-metrics:
    name: Github Metrics CLI theme
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Github Metrics CLI theme
        uses: lowlighter/metrics@latest
        with:
          template: terminal
          filename: metrics.terminal.svg
          base: header, metadata
          token: ${{ secrets.METRICS_TOKEN }}
